---
- hosts: all
  vars:
    packages: [ 'apt-transport-https', 'etckeeper', 'ca-certificates', 'gnupg2', 'software-properties-common' ]
    log_dir: $HOME/logs
  tasks:
    - name: Create log directories
      file:
        path: "{{ log_dir }}"
        state: directory
        mode: 0750

    - name: Install remote apt deps
      apt:
        name: "{{ packages }}"
        state: present

    - name: Add Docker apt-key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker's APT repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian stretch stable
        state: present
        filename: 'docker'

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes' APT repository
      apt_repository:
        # Oddly enough, the stretch repo contains almost no packages...
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'

    - name: Install kubelet
      apt:
        name: kubelet=1.14.0-00
        state: present
        update_cache: true

    - name: Install kubeadm
      apt:
        name: kubeadm=1.14.0-00
        state: present

- hosts: kmaster
  tasks:
    - name: Install kubectl=1.14.0-00
      apt:
        name: kubectl
        state: present
        force: yes
