- hosts: kmaster
  tasks:
    - name: Create mount point
      file:
         path: /data
         state: directory
         mode: '0755'
         owner: nobody
         group: nogroup

    - name: Install NFS
      apt:
        name: nfs-kernel-server
        state: present

    - name: Configure exports
      lineinfile:
        path: /etc/exports
        regexp: '^/data'
        line: /data 10.244.0.0/16(rw,all_squash)

    - name: Restart NFS
      service:
        name: nfs-kernel-server
        state: restarted

- hosts: nodes
  tasks:
    - name: Create mount point
      file:
        path: /mnt/nfs-shared
        state: directory

    - name: install NFS client
      apt:
        name: nfs-common
        state: present

    - name: mount nfs share
      mount:
        src: 10.244.0.1:/data
        path: /shared
        fstype: nfs
        state: mounted

