apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"nginx-deployment-ss","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.7.9","name":"nginx","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/etc/nginx/conf.d","name":"basic-config"}]}],"volumes":[{"configMap":{"name":"basic-config"},"name":"basic-config"}]}}}}
  creationTimestamp: "2019-08-22T07:33:28Z"
  generation: 14
  labels:
    app: nginx
  name: nginx-deployment-ss
  namespace: default
  resourceVersion: "152662"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx-deployment-ss
  uid: 2281a2be-c4af-11e9-aa8f-224398b1ac7c
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 20
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    annotations:
      kubernetes.io/change-cause: "update image to 1.8.0"
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - env:
        - name: EXTRA_VALUE
          valueFrom:
            configMapKeyRef:
              key: extra-param
              name: basic-config
        image: nginx:1.8.0
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: my-conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: basic-config
        name: my-conf
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2019-08-22T07:33:28Z"
    lastUpdateTime: "2019-08-22T09:11:45Z"
    message: ReplicaSet "nginx-deployment-ss-6559544b56" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-08-22T09:46:54Z"
    lastUpdateTime: "2019-08-22T09:46:54Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 14
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
